Golangci lint
ojung/tome pull request #11
Opened 2020-11-13 21:12 UTC by gesundkrank

2020-11-14 21:09 UTC, ojung commented
The CI looks broken.
Also, the stages are run twice because this is a PR and a push.

2020-11-14 21:09 UTC, ojung requested changes
The CI looks broken.
Also, the stages are run twice because this is a PR and a push.

2020-11-14 21:12 UTC, gesundkrank commented
What do you mean by broken? `Build` was replaced by `Build (ubuntu-latest)` and `Build (macos-latest)`. We'll have to change that in the project conf.

We could remove it for pull_requests. But I would prefer that the CI runs for every push. Not only PRs.

2020-11-15 15:35 UTC, ojung approved these changes

2020-11-15 15:43 UTC, merged